@startuml
'https://plantuml.com/sequence-diagram

总部产品运营 -> 商品中心: 商品列表查询
商品中心 --> 总部产品运营: 1. 商品列表查询接口
总部产品运营 -> 商品中心: 查看商品详情
商品中心 --> 总部产品运营: 2. 商品详情接口
note over 商品中心: 当前版本的商品信息，以及所属的商品版本信息列表
group 创建商品
总部产品运营 -> 商品中心: 发起商品创建请求
商品中心 --> 总部产品运营: 3. 创建商品初始化接口
note left #FFAAAA: 返回规则定义
note over 商品中心#FFAAAA: numen提供客户类型
group 新增版本
总部产品运营 -> 商品中心: 发起添加产品请求
商品中心 --> 总部产品运营: 4. 平台产品列表查询接口
note over 商品中心: 根据平台类型，商品类型，收费模式筛选销售阶段的平台产品
group 添加属性
总部产品运营 -> 商品中心: 发起添加属性请求
商品中心 --> 总部产品运营: 5. 数量属性列表查询接口
end
总部产品运营 -> 商品中心: 保存商品版本请求
商品中心 --> 总部产品运营: 6. 商品版本保存接口
end
总部产品运营 -> 商品中心: 保存商品请求
商品中心 --> 总部产品运营: 7. 商品保存接口
end
group 上/下架操作
总部产品运营 -> 商品中心: 发起商品上/下架请求
商品中心 --> 总部产品运营: 8. 商品上/下架保存接口
note over 商品中心: 上架，下架，修改保存业务信息，修改审核状态为审核中并提交审核工作流
end
group 商品修改
总部产品运营 -> 商品中心: 发起商品修改请求
商品中心 --> 总部产品运营: 9. 修改前置校验接口
note left #FFAAAA:  存在申请中不允许修改，权限控制？？
总部产品运营 -> 商品中心: 进入修改页面
商品中心 --> 总部产品运营: 2. 商品详情接口
note over 商品中心: 商品版本的新增接口复用
总部产品运营 -> 商品中心: 修改提交
商品中心 --> 总部产品运营: 10. 商品信息修改接口
end
group 审核流程
审核工作流 -> 商品中心: 返回审核结果
商品中心 --> 商品中心: 11. 审核结果消息通知
总部产品运营 -> 商品中心: 查看申请详情
商品中心 --> 总部产品运营: 12. 查看商品审核信息接口
end

@enduml