@startuml
'https://plantuml.com/activity-diagram-beta

skinparam Activity {
	BorderColor Black
	BackgroundColor PHYSICAL
}


start
:校验必传字段;
#red:同商品保存的校验;
:查询商品的基本信息;
:查询商品关联的审核记录;
:校验是否商品是否存在审核中的申请，存在则报错;
:保存修改记录;
if(商品状态 == 待上架) then(true)
#red:组装需要入库的商品数据;
#red:更新商品基础信息，规格基础信息，类目表;
#red:批量逻辑删除商品业务约束信息，规格销售规则信息，规格属性，规格属性定义;
#red:批量逻辑删除sku产品模块范围，计价模块相关信息;
#red:保存修改后的商品信息;
else if(商品状态 == 已上架)
:保存到业务变更记录表，业务场景==增加商品版本;
:调用审核流，发起审核;
:记录审核信息;
else(商品状态 == 已下架)
:查询最新的商品信息;
:组装商品信息，设置新的商品version;
:复制原商品的开票信息，关联到修改后的商品;
#red:设置新的商品规格的version，关联修改后的商品version;
#red:设置新的sku的version，关联修改后的商品规格version;
#red:需要入库的数据组装;
#red:批量保存升版后的数据;
endif
stop

@enduml