
@startuml
'https://plantuml.com/activity-diagram-beta
skinparam Activity {
	BorderColor Black
	BackgroundColor PHYSICAL
}


start
:根据流程实例id找到对应的审核记录;
:根据业务操作id找到业务场景记录;
:获取分布式锁，防止并发修改;
if(审核意见==同意&&业务场景==商品上架)
:商品状态变更为已上架;
else if(审核意见==同意&&业务场景==商品下架)
:商品状态变更为已下架;
else if(审核意见==同意&&业务场景==商品修改)
:查询业务记录;
:从业务记录内容中获取修改后的商品对象;
if(修改了商品信息?) then(yes)
partition 新增商品信息 {
:修改后的商品的历史版本升版;
:保存新版本的商品基础信息;
:保存新版本的商品类目项，业务约束;
}
else()
endif
partition 遍历商品版本列表,新增商品版本 {
:保存商品版本，商品的历史版本为最新;
:批量保存新版本的平台产品列表，销售规则;
partition 遍历定价策略列表 {
:保存新版本的定价策略;
:批量保存新版本的定价策略内容列表，定价策略id = 定价策略主键;
}
}
else if(审核意见==同意&&业务场景==商品版本新增)
:查询业务记录;
:从业务记录内容中获取商品版本对象;
partition 保存商品版本,遍历商品版本列表 {
:保存商品版本信息，生成商品版本编码和历史版本;
:批量保存平台产品列表，销售规则;
partition 遍历定价策略列表 {
:保存定价策略;
:批量保存定价策略内容列表，定价策略id = 定价策略主键;
}
}
else if(审核意见==不同意)
endif
:记录审核的结果（审核人，审核时间，审核内容）;
:释放分布式锁;

stop

@enduml

