@startuml
'https://plantuml.com/activity-diagram-beta

start
:入参校验;
if(业务操作==商品上架)
#red:校验关联的平台产品是否可售，平台产品状态 != 销售，则报错;
#red:校验关联的类目是否可用，类目停用则报错;
#red:校验关联的属性是否可用，属性停用则报错;
#red:校验是否设置开票项目，未设置则报错;
else if(业务操作==商品下架)
#red:校验当前商品状态是否为已上架，不是则报错;
endif
#red:校验商品是否存在待审核的申请，存在则报错;
:记录业务变更信息;
:发起工作流，获得审核流程实例id;
:记录审核记录信息，审核状态为待审核;
stop

@enduml
