@startuml
'https://plantuml.com/activity-diagram-beta
skinparam Activity {
	BorderColor Black
	BackgroundColor PHYSICAL
}


start
:校验关联的类目是否可用，类目停用则报错;
:校验商品的收费模式;
note left: 1. 按次收费 和 时间收费仅选择预付费;按量付费仅能选择后付费
if(是否传入商品规格信息) then(存在)
partition 商品规格校验 {
if(存在数量或枚举属性？) then(存在)
:校验属性;
note left: 1. 数量属性和枚举属性不能同时选\n2. 属性状态生效\n3. 按量收费必须存在数量属性\n4. 数量属性选择一个，枚举属性最多五个
if(属性类型?) then(枚举属性)
:校验枚举属性值，枚举属性最多十个;
:校验枚举属性的属性值乘积不超过100;
else(数量属性)
:校验起售数(0,999999],最大购买数[起售数的值，999999999];
:步长校验，步长长(0,999999]，且 最大购买数-起售数）/步长为整数；\n按量步长[1，正无穷);
endif
endif
:销售规则校验;
}
else(不存在)
#red:保存失败,商品至少需要一个规格;
end
endif
partition 遍历sku {
if(存在枚举属性？) then(是)
:校验资源包;
else(否)
:校验关联的产品模块;
endif
:校验价格策略的设置;
}
stop

@enduml
