@startuml
'https://plantuml.com/activity-diagram-beta

skinparam Activity {
	BorderColor Black
	BackgroundColor PHYSICAL
}


start
:传入:商品信息;

:比较商品信息的前后变更，记录变更内容;
:保存变更内容到业务记录表;

if(收费模式==按时间收费)
:校验关联的产品性质是否为功能服务，总量恒定资源，且平台类型相同，已上架销售中，关联产品数量不超过10个;
if(是否包含总量恒定或总量递减资源) then(是)
:校验是否有且仅有一个数量属性,属性未被停用;
endif
if(是否包含功能服务) then(是)
:校验属性是否为固定数量，不是则报错;
else(否)
endif
if(属性?) then(固定数量)
:校验添加的固定数量;
note left:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
else(单位数量)
:校验添加的单位数量;
note right:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
endif
:校验是否存在销售份数，存在则报错;
else if(收费模式==按次收费)
:校验是否仅关联一个总量递减资源性质的产品，且平台类型相同，已上架销售中;
:校验是否有且仅有了一个数量属性，属性未被停用;
:校验是否配置失效时间;
if(属性?) then(固定数量)
:校验添加的固定数量;
note left:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
else(单位数量)
:校验添加的单位数量;
note right:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
endif
else if(收费模式==按量计费)
:校验是否仅关联一个总量递减资源性质的产品，且平台类型相同，已上架销售中;
:校验是否有且仅有一个数量属性，属性未被停用;
:校验是否选择了结算周期;
:校验是否存在销售份数，存在则报错;
endif
if(商品状态==待上架 || 商品状态==已下架) then(true)
:商品版本关联的商品的历史版本升版;
:更新商品版本的信息，商品版本的历史版本修改;
:更新所属商品关联的其他商品版本的历史版本;
else(false)
:发起审核流程;
:流程信息保存到审核信息表中，与业务记录表关联;
endif

stop

@enduml


if(收费模式==按时间收费)
:校验关联的产品性质是否为功能服务，总量恒定资源，总量递减资源，且平台类型相同，已上架销售中，关联产品数量不超过10个;
if(是否包含总量恒定或总量递减资源) then(是)
:校验是否有且仅有一个数量属性,属性未被停用;
endif
if(是否包含功能服务) then(是)
:校验属性是否为固定数量，不是则报错;
else(否)
endif
if(属性?) then(固定数量)
:校验添加的固定数量;
note left:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
else(单位数量)
:校验添加的单位数量;
note right:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
endif
:校验是否存在销售份数，存在则报错;
else if(收费模式==按次收费)
:校验是否仅关联一个总量递减资源性质的产品，且平台类型相同，已上架销售中;
:校验是否有且仅有了一个数量属性，属性未被停用;
:校验是否配置失效时间;
if(属性?) then(固定数量)
:校验添加的固定数量;
note left:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
else(单位数量)
:校验添加的单位数量;
note right:1.最多支持20个\n2.后一个数量大于前一个数量\n3.价格大于0
endif
else if(收费模式==按量计费)
:校验是否仅关联一个总量递减资源性质的产品，且平台类型相同，已上架销售中;
:校验是否有且仅有一个数量属性，属性未被停用;
:校验是否选择了结算周期;
:校验是否存在销售份数，存在则报错;
endif
