@startuml
'https://plantuml.com/sequence-diagram

前端 -> cmc: 资源包新增
cmc --> 前端: 新增成功
group 修改资源包
前端 -> cmc: 修改资源包前置校验
cmc --> 前端: 校验成功
前端 -> cmc: 查看资源包详情
cmc --> 前端: 返回资源包详情
前端 -> cmc: 修改资源包
cmc -> 工作流: 发起工作流
工作流 --> cmc: 审核回调通知
end
group 上下架资源包
前端 -> cmc: 上下架资源包前置校验
cmc --> 前端: 校验成功
前端 -> cmc: 资源包上下架
cmc --> 工作流: 发起工作流
工作流 -> cmc: 审核回调通知
end
前端 -> cmc: 资源包列表查询
cmc --> 前端: 返回成功
前端 -> cmc: 通过审核id查询资源包审核信息
cmc --> 前端: 返回审核信息
group 新增商品环节
前端 -> cmc: 展示可选的资源包，支持模糊搜索
cmc --> 前端: 返回结果
end
@enduml